#!/usr/bin/env python3

import rospy

from spar_msgs.msg import ArucoLocalisation

if __name__ == "__main__":
    rospy.init_node('node_name')

    # Create an ArUco publisher
    roi_pub = rospy.Publisher("/aruco", ArucoLocalisation, queue_size=10, latch = True)
    rospy.loginfo('Created Publisher Node')
    # Initialise the ArUco publisher message type
    roi_msg_out = ArucoLocalisation()
    # Update message parameters
    roi_msg_out.aruco_id = 50
    # Publish the ROI message
    roi_pub.publish(roi_msg_out)
    rospy.loginfo('Published Message')
    

    try:
        rospy.spin()
    except rospy.ROSInterrupyException:
        pass